name: Deploying my portfolio
run-name: ${{ github.actor }} is automating the workflow
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Updating the domain
        run: echo "Your GitHub Pages site is live at https://SarvariHarshitha.github.io/portfolio/"

